### ISSUE TITLE
Scale width and height

### ISSUE THREAD

**Issue by shepherdscribe** [maartenpaauw/undraw#13]
Hi, I wanna use this package but I can't customize the image dimension. Manually editing them would be time consuming.

**Comment by maartenpaauw** [comment]
Maybe wrap the illustration within a `div` with custom dimensions?

**Comment by maartenpaauw** [comment]
I've reopened this issue because I faced the scaling problem today. Is there a good way to solve it? Will removing the width and height attribute do its job?

**Comment by maartenpaauw** [comment]
I've released a release candidate (versioned as `3.0.0-rc1`). This version has all illustrations without the first `width` and `height` attribute. It seems to work for me. Let me know what you think!

**Comment by maartenpaauw** [comment]
Fixed in version 3.0.0
